// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0zWyKjkJKwCtqv8ycaivcZQVm-Ze74Uo',
    appId: '1:646581409212:web:537995e8b8b56d650507b9',
    messagingSenderId: '646581409212',
    projectId: 'database-bec27',
    authDomain: 'database-bec27.firebaseapp.com',
    storageBucket: 'database-bec27.appspot.com',
    measurementId: 'G-X5JVW3MDZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3w19mVQoLf_4GkfxVTAQoSE5XRPNt7pM',
    appId: '1:646581409212:android:f0520a3bab9bef510507b9',
    messagingSenderId: '646581409212',
    projectId: 'database-bec27',
    storageBucket: 'database-bec27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwmmh-CjTdR2OB9aOwy2f7Kjr9QkIgHSM',
    appId: '1:646581409212:ios:9a76093519d264270507b9',
    messagingSenderId: '646581409212',
    projectId: 'database-bec27',
    storageBucket: 'database-bec27.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwmmh-CjTdR2OB9aOwy2f7Kjr9QkIgHSM',
    appId: '1:646581409212:ios:9a76093519d264270507b9',
    messagingSenderId: '646581409212',
    projectId: 'database-bec27',
    storageBucket: 'database-bec27.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0zWyKjkJKwCtqv8ycaivcZQVm-Ze74Uo',
    appId: '1:646581409212:web:09f05f0fa65492fb0507b9',
    messagingSenderId: '646581409212',
    projectId: 'database-bec27',
    authDomain: 'database-bec27.firebaseapp.com',
    storageBucket: 'database-bec27.appspot.com',
    measurementId: 'G-HPGBYGMJ5Z',
  );
}
